# Generated by Django 5.0.1 on 2024-01-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
