# Generated by Django 5.0.1 on 2024-01-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_spotify", "0003_alter_room_id_alter_room_room_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="room_code",
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
