# Generated by Django 5.0.1 on 2024-02-07 23:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api_spotify", "0008_spotifyuser_spotifyusertoken"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SpotifyUser",
        ),
    ]
