# Generated by Django 5.0.1 on 2024-02-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_spotify", "0009_delete_spotifyuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spotifyusertoken",
            name="user",
        ),
        migrations.AddField(
            model_name="spotifyusertoken",
            name="email",
            field=models.EmailField(
                default="token@email.com", max_length=254, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="spotifyusertoken",
            name="username",
            field=models.CharField(default="tokenuser", max_length=100),
            preserve_default=False,
        ),
    ]
