# Generated by Django 5.0.1 on 2024-02-09 19:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api_spotify", "0011_room_room_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="spotifyusertoken",
            old_name="username",
            new_name="user_session",
        ),
        migrations.RemoveField(
            model_name="spotifyusertoken",
            name="email",
        ),
    ]
